### ISSUE TITLE
Improvement todos for welcome.md and instances.md

### ISSUE THREAD

**Issue by msappir** [Toootim/Resources#2]
- [ ] add explanation of toot privacy/exposure to welcome.md
- [ ] take points from nolan's intro
- [ ] remove toot.cat from instances as it's not open reg anymore

**Comment by msappir** [comment]
Feel free to add more. I'll maintain these for the time being but if it become too much someone else will probably turn up.

**Comment by playmobilmeister** [comment]
@msappir @seefood @yair 
💡 add a link to welcome.md somwhere more visible, assuming it's possible to customize, and make it appear the top of [the about-->>more page](https://tooot.im/about/more)
examples:
![1](https://user-images.githubusercontent.com/33288162/188865573-3099fd9e-a9ec-4760-b440-a37f0b63e518.png)
![2](https://user-images.githubusercontent.com/33288162/188865581-b46ed471-b214-489d-a6f4-89fd278d785f.png)

💡 Unify all Tips under #טיפים in a document for newcomers - I can do this

💡 welcome.md - add some screenshots with Hebrew instructions - I can do this

💡 update instances.md and check all links 

💡 Bot that will send some helper messages to newbies, [as discussed](https://tooot.im/@yoavzack/108883930064477254) by @yair  & @yoavzack@tooot.im
